# Generated by Django 3.2 on 2024-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('responsable', models.CharField(max_length=15)),
                ('prioridad', models.IntegerField()),
            ],
        ),
    ]
